# Generated by Django 5.1.7 on 2026-03-13 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='创建人')),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='更新人')),
                ('role_code', models.CharField(max_length=64, unique=True, verbose_name='角色编码')),
                ('role_name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('data_scope', models.CharField(choices=[('SELF', '仅本人'), ('DEPT', '本部门'), ('DEPT_AND_CHILD', '本部门及子部门'), ('ALL', '全部')], default='SELF', max_length=32, verbose_name='数据权限范围')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'sys_role',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='创建人')),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='更新人')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='登录账号')),
                ('real_name', models.CharField(db_index=True, max_length=100, verbose_name='真实姓名')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号')),
                ('security_clearance_level', models.CharField(choices=[('PUBLIC', '公开'), ('INTERNAL', '内部'), ('SECRET', '秘密'), ('CONFIDENTIAL', '机密'), ('TOP_SECRET', '绝密')], db_index=True, default='INTERNAL', max_length=16, verbose_name='最高密级')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('failed_login_count', models.PositiveIntegerField(default=0, verbose_name='连续失败次数')),
                ('last_failed_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后失败时间')),
                ('lock_until_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定截止时间')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('last_login_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='最后登录 IP')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否后台人员')),
                ('dept', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizations.department', verbose_name='所属主部门')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'sys_user',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SystemPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('permission_code', models.CharField(max_length=100, unique=True, verbose_name='权限编码')),
                ('permission_name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('permission_type', models.CharField(choices=[('MENU', '菜单'), ('BUTTON', '按钮'), ('API', '接口')], default='MENU', max_length=32, verbose_name='权限类型')),
                ('module_name', models.CharField(db_index=True, max_length=64, verbose_name='模块名称')),
                ('route_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='路由路径')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序值')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.systempermission', verbose_name='上级权限')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'sys_permission',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.systempermission')),
            ],
            options={
                'verbose_name': '角色权限关联',
                'verbose_name_plural': '角色权限关联',
                'db_table': 'sys_role_permission',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='accounts.RolePermission', to='accounts.systempermission', verbose_name='权限'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色关联',
                'verbose_name_plural': '用户角色关联',
                'db_table': 'sys_user_role',
            },
        ),
        migrations.AddField(
            model_name='systemuser',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='accounts.UserRole', to='accounts.role', verbose_name='角色'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uniq_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='uniq_user_role'),
        ),
    ]
