# Generated by Django 5.1.7 on 2026-03-13 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0002_archivefile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFileAccessTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='用户名快照')),
                ('real_name', models.CharField(blank=True, default='', max_length=100, verbose_name='姓名快照')),
                ('access_action', models.CharField(choices=[('PREVIEW', '预览'), ('DOWNLOAD', '下载')], db_index=True, max_length=16, verbose_name='访问动作')),
                ('token', models.CharField(db_index=True, default='', max_length=64, unique=True, verbose_name='访问票据')),
                ('purpose', models.CharField(blank=True, max_length=255, null=True, verbose_name='下载用途')),
                ('watermark_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='水印文本')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='失效时间')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='访问次数')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后访问时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='下载使用时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('archive_file', models.ForeignKey(db_column='archive_file_id', on_delete=django.db.models.deletion.CASCADE, related_name='access_tickets', to='archives.archivefile', verbose_name='档案文件')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_file_access_tickets', to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '档案文件访问票据',
                'verbose_name_plural': '档案文件访问票据',
                'db_table': 'archive_file_access_ticket',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='用户名快照')),
                ('real_name', models.CharField(blank=True, default='', max_length=100, verbose_name='姓名快照')),
                ('module_name', models.CharField(db_index=True, max_length=64, verbose_name='模块名称')),
                ('action_code', models.CharField(db_index=True, max_length=64, verbose_name='动作编码')),
                ('biz_type', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='业务类型')),
                ('biz_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='业务标识')),
                ('target_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='目标摘要')),
                ('result_status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败'), ('DENIED', '拒绝')], db_index=True, default='SUCCESS', max_length=16, verbose_name='结果状态')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True, verbose_name='客户端 IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='客户端 UA')),
                ('request_method', models.CharField(blank=True, max_length=16, null=True, verbose_name='请求方法')),
                ('request_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='请求路径')),
                ('extra_data_json', models.JSONField(blank=True, default=dict, verbose_name='补充数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'sys_audit_log',
                'ordering': ['-id'],
            },
        ),
    ]
