# Generated by Django 5.1.7 on 2026-03-13 08:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveStorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='创建人')),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='更新人')),
                ('warehouse_name', models.CharField(db_index=True, max_length=100, verbose_name='库房名称')),
                ('area_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='分区名称')),
                ('cabinet_code', models.CharField(db_index=True, max_length=64, verbose_name='柜号')),
                ('rack_code', models.CharField(max_length=64, verbose_name='架号')),
                ('layer_code', models.CharField(max_length=64, verbose_name='层号')),
                ('box_code', models.CharField(max_length=64, verbose_name='盒号')),
                ('full_location_code', models.CharField(max_length=255, unique=True, verbose_name='完整位置编码')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='是否可用')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '实体位置',
                'verbose_name_plural': '实体位置',
                'db_table': 'archive_storage_location',
                'ordering': ['warehouse_name', 'cabinet_code', 'rack_code', 'layer_code', 'box_code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='创建人')),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='更新人')),
                ('archive_code', models.CharField(max_length=64, unique=True, verbose_name='档号')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='题名')),
                ('year', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='年度')),
                ('retention_period', models.CharField(db_index=True, max_length=32, verbose_name='保管期限')),
                ('security_level', models.CharField(choices=[('PUBLIC', '公开'), ('INTERNAL', '内部'), ('SECRET', '秘密'), ('CONFIDENTIAL', '机密'), ('TOP_SECRET', '绝密')], db_index=True, max_length=16, verbose_name='密级')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_SCAN', '待扫描'), ('PENDING_CATALOG', '待编目'), ('ON_SHELF', '已上架'), ('BORROWED', '借出中'), ('DESTROY_PENDING', '销毁审批中'), ('DESTROYED', '已销毁'), ('FROZEN', '冻结')], db_index=True, default='DRAFT', max_length=32, verbose_name='档案状态')),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='责任人')),
                ('formed_at', models.DateField(blank=True, null=True, verbose_name='形成日期')),
                ('keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='关键词')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='页数')),
                ('carrier_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='载体类型')),
                ('current_borrow_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='当前借阅单 ID')),
                ('catalog_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='编目完成时间')),
                ('shelved_at', models.DateTimeField(blank=True, null=True, verbose_name='上架时间')),
                ('responsible_dept', models.ForeignKey(blank=True, db_column='responsible_dept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archive_records', to='organizations.department', verbose_name='责任部门')),
                ('location', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archive_records', to='archives.archivestoragelocation', verbose_name='当前实体位置')),
            ],
            options={
                'verbose_name': '档案',
                'verbose_name_plural': '档案',
                'db_table': 'archive_record',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveMetadataRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField(verbose_name='修订版本号')),
                ('changed_fields_json', models.JSONField(verbose_name='变更字段')),
                ('snapshot_json', models.JSONField(verbose_name='完整快照')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='修订说明')),
                ('revised_by', models.PositiveBigIntegerField(db_index=True, verbose_name='修订人')),
                ('revised_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修订时间')),
                ('archive', models.ForeignKey(db_column='archive_id', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='archives.archiverecord', verbose_name='档案')),
            ],
            options={
                'verbose_name': '档案修订记录',
                'verbose_name_plural': '档案修订记录',
                'db_table': 'archive_metadata_revision',
                'ordering': ['-revision_no', '-id'],
                'constraints': [models.UniqueConstraint(fields=('archive', 'revision_no'), name='uniq_archive_revision_no')],
            },
        ),
        migrations.CreateModel(
            name='ArchiveBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code_type', models.CharField(choices=[('BARCODE', '条码'), ('QRCODE', '二维码')], db_index=True, max_length=16)),
                ('code_content', models.CharField(max_length=255, verbose_name='编码内容')),
                ('image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片路径')),
                ('print_count', models.PositiveIntegerField(default=0, verbose_name='打印次数')),
                ('last_printed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后打印时间')),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='创建人')),
                ('archive', models.ForeignKey(db_column='archive_id', on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='archives.archiverecord', verbose_name='档案')),
            ],
            options={
                'verbose_name': '档案条码',
                'verbose_name_plural': '档案条码',
                'db_table': 'archive_barcode',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('archive', 'code_type'), name='uniq_archive_code_type')],
            },
        ),
    ]
