# Generated by Django 5.1.7 on 2026-03-13 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_task_item_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='扫描任务明细 ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='缩略图路径')),
                ('file_ext', models.CharField(db_index=True, max_length=16, verbose_name='文件扩展名')),
                ('mime_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='MIME 类型')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='页数')),
                ('file_source', models.CharField(choices=[('SCAN_UPLOAD', '扫描上传'), ('MANUAL_UPLOAD', '手工上传')], db_index=True, default='SCAN_UPLOAD', max_length=32, verbose_name='文件来源')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序值')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='提取文本')),
                ('status', models.CharField(choices=[('PROCESSING', '处理中'), ('ACTIVE', '有效'), ('FAILED', '处理失败')], db_index=True, default='ACTIVE', max_length=16, verbose_name='文件状态')),
                ('uploaded_by', models.PositiveBigIntegerField(db_index=True, verbose_name='上传人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('archive', models.ForeignKey(db_column='archive_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='archives.archiverecord', verbose_name='档案')),
            ],
            options={
                'verbose_name': '档案文件',
                'verbose_name_plural': '档案文件',
                'db_table': 'archive_file',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
