# Generated by Django 5.1.7 on 2026-03-13 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='创建人')),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='更新人')),
                ('dept_code', models.CharField(max_length=64, unique=True, verbose_name='部门编码')),
                ('dept_name', models.CharField(db_index=True, max_length=100, verbose_name='部门名称')),
                ('dept_path', models.CharField(default='/', max_length=500, verbose_name='层级路径')),
                ('dept_level', models.PositiveIntegerField(default=1, verbose_name='层级深度')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序值')),
                ('approver_user_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='审批负责人')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organizations.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'org_department',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
