# Generated by Django 5.1.7 on 2026-03-13 09:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0002_archivefile'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='创建人')),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='更新人')),
                ('application_no', models.CharField(max_length=64, unique=True, verbose_name='申请编号')),
                ('purpose', models.CharField(max_length=500, verbose_name='借阅用途')),
                ('expected_return_at', models.DateTimeField(db_index=True, verbose_name='预计归还时间')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_APPROVAL', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已驳回'), ('WITHDRAWN', '已撤回'), ('CHECKED_OUT', '借出中'), ('OVERDUE', '已超期'), ('RETURNED', '已归还')], db_index=True, default='DRAFT', max_length=32, verbose_name='借阅状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批通过时间')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='驳回时间')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('checkout_at', models.DateTimeField(blank=True, null=True, verbose_name='实际借出时间')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间')),
                ('reject_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='驳回原因')),
                ('is_overdue', models.BooleanField(db_index=True, default=False, verbose_name='是否超期')),
                ('overdue_days', models.PositiveIntegerField(default=0, verbose_name='超期天数')),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.PROTECT, related_name='borrow_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('applicant_dept', models.ForeignKey(db_column='applicant_dept_id', on_delete=django.db.models.deletion.PROTECT, related_name='borrow_applications', to='organizations.department', verbose_name='申请部门')),
                ('archive', models.ForeignKey(db_column='archive_id', on_delete=django.db.models.deletion.PROTECT, related_name='borrow_applications', to='archives.archiverecord', verbose_name='档案')),
                ('current_approver', models.ForeignKey(blank=True, db_column='current_approver_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_borrow_approvals', to=settings.AUTH_USER_MODEL, verbose_name='当前审批人')),
            ],
            options={
                'verbose_name': '借阅申请',
                'verbose_name_plural': '借阅申请',
                'db_table': 'borrow_application',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BorrowApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('action', models.CharField(choices=[('APPROVE', '通过'), ('REJECT', '驳回')], db_index=True, max_length=16, verbose_name='审批动作')),
                ('opinion', models.CharField(blank=True, max_length=500, null=True, verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='审批时间')),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='borrowing.borrowapplication', verbose_name='借阅申请')),
                ('approver', models.ForeignKey(db_column='approver_id', on_delete=django.db.models.deletion.PROTECT, related_name='borrow_approval_records', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '借阅审批记录',
                'verbose_name_plural': '借阅审批记录',
                'db_table': 'borrow_approval_record',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BorrowCheckoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('checkout_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='出库时间')),
                ('expected_return_at', models.DateTimeField(db_index=True, verbose_name='预计归还时间')),
                ('location_snapshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='借出前位置快照')),
                ('checkout_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='出库备注')),
                ('application', models.OneToOneField(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, related_name='checkout_record', to='borrowing.borrowapplication', verbose_name='借阅申请')),
                ('archive', models.ForeignKey(db_column='archive_id', on_delete=django.db.models.deletion.PROTECT, related_name='borrow_checkout_records', to='archives.archiverecord', verbose_name='档案')),
                ('borrower', models.ForeignKey(db_column='borrower_id', on_delete=django.db.models.deletion.PROTECT, related_name='borrow_checkout_received_records', to=settings.AUTH_USER_MODEL, verbose_name='领取人')),
                ('operator', models.ForeignKey(db_column='operator_id', on_delete=django.db.models.deletion.PROTECT, related_name='borrow_checkout_operated_records', to=settings.AUTH_USER_MODEL, verbose_name='办理档案员')),
            ],
            options={
                'verbose_name': '出库登记',
                'verbose_name_plural': '出库登记',
                'db_table': 'borrow_checkout_record',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BorrowReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('return_status', models.CharField(choices=[('SUBMITTED', '已提交归还'), ('CONFIRMED', '已确认入库'), ('REJECTED', '归还验收不通过')], db_index=True, default='SUBMITTED', max_length=16, verbose_name='归还确认状态')),
                ('handover_type', models.CharField(choices=[('PHOTO', '照片'), ('DOCUMENT', '交接单'), ('BOTH', '照片和交接单')], max_length=16, verbose_name='交接类型')),
                ('handover_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='交接说明')),
                ('returned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='归还提交时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认入库时间')),
                ('confirm_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='验收备注')),
                ('application', models.OneToOneField(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, related_name='return_record', to='borrowing.borrowapplication', verbose_name='借阅申请')),
                ('archive', models.ForeignKey(db_column='archive_id', on_delete=django.db.models.deletion.PROTECT, related_name='borrow_return_records', to='archives.archiverecord', verbose_name='档案')),
                ('location_after_return', models.ForeignKey(blank=True, db_column='location_after_return_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrow_return_records', to='archives.archivestoragelocation', verbose_name='归还后位置')),
                ('received_by_user', models.ForeignKey(blank=True, db_column='received_by_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrow_return_received_records', to=settings.AUTH_USER_MODEL, verbose_name='验收档案员')),
                ('returned_by_user', models.ForeignKey(db_column='returned_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='borrow_return_submitted_records', to=settings.AUTH_USER_MODEL, verbose_name='归还提交人')),
            ],
            options={
                'verbose_name': '归还记录',
                'verbose_name_plural': '归还记录',
                'db_table': 'borrow_return_record',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BorrowReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('attachment_type', models.CharField(choices=[('PHOTO', '照片'), ('HANDOVER_DOC', '交接单')], db_index=True, max_length=16, verbose_name='附件类型')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('uploaded_by', models.PositiveBigIntegerField(db_index=True, verbose_name='上传人')),
                ('return_record', models.ForeignKey(db_column='return_record_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='borrowing.borrowreturnrecord', verbose_name='归还记录')),
            ],
            options={
                'verbose_name': '归还附件',
                'verbose_name_plural': '归还附件',
                'db_table': 'borrow_return_attachment',
                'ordering': ['id'],
            },
        ),
    ]
