# Generated by Django 5.1.7 on 2026-03-13 10:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowReminderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reminder_type', models.CharField(choices=[('BEFORE_DUE', '到期前提醒'), ('DUE_TODAY', '到期当天提醒'), ('OVERDUE', '超期提醒')], db_index=True, max_length=16, verbose_name='提醒类型')),
                ('channel', models.CharField(choices=[('SITE', '站内通知'), ('EMAIL', '邮件')], db_index=True, max_length=16, verbose_name='发送渠道')),
                ('receiver_email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='接收邮箱')),
                ('send_status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败')], db_index=True, default='SUCCESS', max_length=16, verbose_name='发送状态')),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='发送时间')),
                ('content_summary', models.CharField(blank=True, max_length=255, null=True, verbose_name='内容摘要')),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, related_name='reminder_records', to='borrowing.borrowapplication', verbose_name='借阅申请')),
                ('email_task', models.ForeignKey(blank=True, db_column='email_task_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_reminder_records', to='notifications.emailtask', verbose_name='邮件任务')),
                ('notification', models.ForeignKey(blank=True, db_column='notification_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_reminder_records', to='notifications.systemnotification', verbose_name='站内通知')),
                ('receiver_user', models.ForeignKey(blank=True, db_column='receiver_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_reminder_records', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '催还记录',
                'verbose_name_plural': '催还记录',
                'db_table': 'borrow_reminder_record',
                'ordering': ['-sent_at', '-id'],
            },
        ),
    ]
