# Generated by Django 5.1.7 on 2026-03-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_borrowreminderrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowreminderrecord',
            name='send_status',
            field=models.CharField(choices=[('PENDING', '待发送'), ('RUNNING', '发送中'), ('SUCCESS', '成功'), ('FAILED', '失败')], db_index=True, default='PENDING', max_length=16, verbose_name='发送状态'),
        ),
    ]
