# Generated by Django 5.1.7 on 2026-03-13 10:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('receiver_email', models.EmailField(db_index=True, max_length=128, verbose_name='接收邮箱')),
                ('subject', models.CharField(max_length=255, verbose_name='邮件主题')),
                ('content', models.TextField(verbose_name='邮件内容')),
                ('biz_type', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='业务类型')),
                ('biz_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='业务标识')),
                ('send_status', models.CharField(choices=[('PENDING', '待发送'), ('RUNNING', '发送中'), ('SUCCESS', '发送成功'), ('FAILED', '发送失败')], db_index=True, default='PENDING', max_length=16, verbose_name='发送状态')),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='计划发送时间')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发送时间')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('error_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='失败原因')),
                ('receiver_user', models.ForeignKey(blank=True, db_column='receiver_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_tasks', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '邮件任务',
                'verbose_name_plural': '邮件任务',
                'db_table': 'sys_email_task',
                'ordering': ['send_status', '-scheduled_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notification_type', models.CharField(choices=[('BORROW_APPROVAL', '借阅审批通知'), ('BORROW_REMINDER', '催还通知'), ('RETURN_CONFIRM', '归还确认通知'), ('DESTROY_APPROVAL', '销毁审批通知'), ('SYSTEM', '系统通知')], db_index=True, max_length=32, verbose_name='通知类型')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('biz_type', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='业务类型')),
                ('biz_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='业务标识')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '站内通知',
                'verbose_name_plural': '站内通知',
                'db_table': 'sys_notification',
                'ordering': ['is_read', '-created_at', '-id'],
            },
        ),
    ]
