# Generated by Django 5.1.7 on 2026-03-13 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0002_archivefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='创建人')),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='更新人')),
                ('task_no', models.CharField(max_length=64, unique=True, verbose_name='任务编号')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('assigned_user_id', models.PositiveBigIntegerField(db_index=True, verbose_name='指派执行人')),
                ('assigned_by', models.PositiveBigIntegerField(db_index=True, verbose_name='指派人')),
                ('status', models.CharField(choices=[('PENDING', '待开始'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('FAILED', '已失败')], db_index=True, default='PENDING', max_length=16, verbose_name='任务状态')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='档案总数')),
                ('completed_count', models.PositiveIntegerField(default=0, verbose_name='完成数')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
                'db_table': 'scan_task',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FileProcessJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('THUMBNAIL', '缩略图生成'), ('TEXT_EXTRACT', '文本提取')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('PROCESSING', '处理中'), ('SUCCESS', '成功'), ('FAILED', '失败')], db_index=True, default='PENDING', max_length=16, verbose_name='处理状态')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('error_message', models.CharField(blank=True, max_length=500, null=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('archive_file', models.ForeignKey(db_column='archive_file_id', on_delete=django.db.models.deletion.CASCADE, related_name='process_jobs', to='archives.archivefile', verbose_name='档案文件')),
            ],
            options={
                'verbose_name': '文件处理任务',
                'verbose_name_plural': '文件处理任务',
                'db_table': 'file_process_job',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScanTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee_user_id', models.PositiveBigIntegerField(db_index=True, verbose_name='执行人')),
                ('status', models.CharField(choices=[('PENDING', '待上传'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('FAILED', '已失败')], db_index=True, default='PENDING', max_length=16, verbose_name='明细状态')),
                ('uploaded_file_count', models.PositiveIntegerField(default=0, verbose_name='已上传文件数')),
                ('last_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='最后上传时间')),
                ('error_message', models.CharField(blank=True, max_length=500, null=True, verbose_name='异常说明')),
                ('archive', models.ForeignKey(db_column='archive_id', on_delete=django.db.models.deletion.PROTECT, related_name='scan_task_items', to='archives.archiverecord', verbose_name='档案')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='digitization.scantask', verbose_name='扫描任务')),
            ],
            options={
                'verbose_name': '扫描任务明细',
                'verbose_name_plural': '扫描任务明细',
                'db_table': 'scan_task_item',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('task', 'archive'), name='uniq_scan_task_archive')],
            },
        ),
    ]
