# Generated by Django 5.1.7 on 2026-03-13 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0002_archivefile'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestroyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='创建人')),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='更新人')),
                ('application_no', models.CharField(max_length=64, unique=True, verbose_name='申请编号')),
                ('reason', models.CharField(max_length=500, verbose_name='销毁原因')),
                ('basis', models.CharField(max_length=500, verbose_name='销毁依据')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已驳回'), ('EXECUTED', '已执行销毁')], db_index=True, default='PENDING_APPROVAL', max_length=32, verbose_name='销毁状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批通过时间')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='驳回时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('reject_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='驳回原因')),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.PROTECT, related_name='destroy_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('applicant_dept', models.ForeignKey(db_column='applicant_dept_id', on_delete=django.db.models.deletion.PROTECT, related_name='destroy_applications', to='organizations.department', verbose_name='申请部门')),
                ('archive', models.ForeignKey(db_column='archive_id', on_delete=django.db.models.deletion.PROTECT, related_name='destroy_applications', to='archives.archiverecord', verbose_name='档案')),
                ('current_approver', models.ForeignKey(blank=True, db_column='current_approver_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_destroy_approvals', to=settings.AUTH_USER_MODEL, verbose_name='当前审批人')),
            ],
            options={
                'verbose_name': '销毁申请',
                'verbose_name_plural': '销毁申请',
                'db_table': 'destroy_application',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DestroyApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('action', models.CharField(choices=[('APPROVE', '通过'), ('REJECT', '驳回')], db_index=True, max_length=16, verbose_name='审批动作')),
                ('opinion', models.CharField(blank=True, max_length=500, null=True, verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='审批时间')),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='destruction.destroyapplication', verbose_name='销毁申请')),
                ('approver', models.ForeignKey(db_column='approver_id', on_delete=django.db.models.deletion.PROTECT, related_name='destroy_approval_records', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '销毁审批记录',
                'verbose_name_plural': '销毁审批记录',
                'db_table': 'destroy_approval_record',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DestroyExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='执行时间')),
                ('execution_note', models.CharField(max_length=500, verbose_name='执行说明')),
                ('location_snapshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='销毁前位置快照')),
                ('archive_snapshot_json', models.JSONField(default=dict, verbose_name='销毁时档案快照')),
                ('application', models.OneToOneField(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, related_name='execution_record', to='destruction.destroyapplication', verbose_name='销毁申请')),
                ('archive', models.ForeignKey(db_column='archive_id', on_delete=django.db.models.deletion.PROTECT, related_name='destroy_execution_records', to='archives.archiverecord', verbose_name='档案')),
                ('operator', models.ForeignKey(db_column='operator_id', on_delete=django.db.models.deletion.PROTECT, related_name='destroy_execution_records', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '销毁执行记录',
                'verbose_name_plural': '销毁执行记录',
                'db_table': 'destroy_execution_record',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DestroyExecutionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('uploaded_by', models.PositiveBigIntegerField(db_index=True, verbose_name='上传人')),
                ('execution_record', models.ForeignKey(db_column='execution_record_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='destruction.destroyexecutionrecord', verbose_name='销毁执行记录')),
            ],
            options={
                'verbose_name': '销毁执行附件',
                'verbose_name_plural': '销毁执行附件',
                'db_table': 'destroy_execution_attachment',
                'ordering': ['id'],
            },
        ),
    ]
